# Generated by Django 4.2.6 on 2023-10-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("subtitle", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("amount", models.IntegerField()),
                ("image", models.ImageField(upload_to="course/")),
                ("is_active", models.BooleanField(blank=True, default=True)),
            ],
        ),
    ]
