# Generated by Django 4.2.6 on 2023-10-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="details",
            field=models.TextField(default="Dummy details."),
            preserve_default=False,
        ),
    ]
